# Generated by Django 5.1.7 on 2025-03-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_chat_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
